export { default as BerryListPage } from './BerryListPage';
export { default as EggGroupPage } from './EggGroupPage';
export { default as HeadbuttLocationsPage } from './HeadbuttLocationsPage';
export { default as Homepage } from './Homepage';
export { default as ItemListPage } from './ItemListPage';
export { default as ItemPage } from './ItemPage';
export { default as MovePage } from './MovePage';
export { default as MovesListPage } from './MovesListPage';
export { default as NotFoundPage } from './NotFound';
export { default as PokemonPage } from './PokemonPage';
export * from './RegionsPages';
export { default as SpritesPage } from './SpritesPage';
export { default as TypePage } from './TypePage';
