export const typeList = [
  {
    id: 1,
    name: 'normal',
    url: 'https://pokeapi.co/api/v2/type/1/',
    type: 'type',
  },
  {
    id: 2,
    name: 'fighting',
    url: 'https://pokeapi.co/api/v2/type/2/',
    type: 'type',
  },
  {
    id: 3,
    name: 'flying',
    url: 'https://pokeapi.co/api/v2/type/3/',
    type: 'type',
  },
  {
    id: 4,
    name: 'poison',
    url: 'https://pokeapi.co/api/v2/type/4/',
    type: 'type',
  },
  {
    id: 5,
    name: 'ground',
    url: 'https://pokeapi.co/api/v2/type/5/',
    type: 'type',
  },
  {
    id: 6,
    name: 'rock',
    url: 'https://pokeapi.co/api/v2/type/6/',
    type: 'type',
  },
  {
    id: 7,
    name: 'bug',
    url: 'https://pokeapi.co/api/v2/type/7/',
    type: 'type',
  },
  {
    id: 8,
    name: 'ghost',
    url: 'https://pokeapi.co/api/v2/type/8/',
    type: 'type',
  },
  {
    id: 9,
    name: 'steel',
    url: 'https://pokeapi.co/api/v2/type/9/',
    type: 'type',
  },
  {
    id: 10,
    name: 'fire',
    url: 'https://pokeapi.co/api/v2/type/10/',
    type: 'type',
  },
  {
    id: 11,
    name: 'water',
    url: 'https://pokeapi.co/api/v2/type/11/',
    type: 'type',
  },
  {
    id: 12,
    name: 'grass',
    url: 'https://pokeapi.co/api/v2/type/12/',
    type: 'type',
  },
  {
    id: 13,
    name: 'electric',
    url: 'https://pokeapi.co/api/v2/type/13/',
    type: 'type',
  },
  {
    id: 14,
    name: 'psychic',
    url: 'https://pokeapi.co/api/v2/type/14/',
    type: 'type',
  },
  {
    id: 15,
    name: 'ice',
    url: 'https://pokeapi.co/api/v2/type/15/',
    type: 'type',
  },
  {
    id: 16,
    name: 'dragon',
    url: 'https://pokeapi.co/api/v2/type/16/',
    type: 'type',
  },
  {
    id: 17,
    name: 'dark',
    url: 'https://pokeapi.co/api/v2/type/17/',
    type: 'type',
  },
  {
    id: 18,
    name: 'fairy',
    url: 'https://pokeapi.co/api/v2/type/18/',
    type: 'type',
  },
]
